graph TD
    Room1["The Harpies' Nest"] <-->|Broken Door| Room2[Room 2]
    Room1 <-->|Door| Room3["Room 3"]
    Room2 <-.->|"Narrow <br>passageway"| Room4["Ghast lair"]
    Room4 --> Room5["🌒 Room 5: The Crown Beneath the Mire
        → Resolution, reward, or curse. Balance (or unrest) returns to the fen."]
    Room4 <-.->|"Hidden <br>door"| Room6["Underground Lake
    - A serene underground lake with bioluminescent flora and fauna
    -👃Musty and damp
    - 🥾 Slippery rocks and shallow waters
    - 👣 Human sized web feet"]

    %% 🔥 👃 👣 ⚔️ 🔦 ⬅️➡️⬆️⬇️↕️↔️🪤