= Create your pulp hero

When planning your character, make someone who would be up to thwart evil across the globe.
Of course, it is interesting if the character has some reluctance to putting herself in peril (e.g., family at home, a movie to star in, experiments to complete), but a party full of reluctant heroes who all need to be coaxed into action before an adventure creates friction in our story that we want to minimize.

TIP: You can use the setting in Savaged.us at https://savaged.us/s/fxwm2vka to create a character.

== Motivations

.Suggested motivations:
* Money
* Higher purpose (e.g., preserve, protect, redeem)
* Adventure and thrills
* Reputation, glory, and fame
* Professional rivalry
* Redemption

== Races
Heroes are humans.

== Initial rank and advances

The characters begin with 2 advances. 

== Skills

Pulp heroes are more capable than most.
At character creation, they start with 15 skill points as per the "More skill points" setting rule.

.Changed skills
// * Electronics is reskinned as Gadgetry
* Hacking is reskinned as Cryptopgraphy + 
It assumes some knowledge of codes and code breaking (e.g., Morse code) and mathematics

.Removed skills
* Focus, applies to the Arcane Background (Gifted)
* Faith, applies to the Arcane Background (Miracles)
* Language (see the Multiple Languages setting rules in SWADE p 149)
* Psionics, applies to the Arcane Background (Psionics)
* Spellcasting, applies to the Arcane Background (Magic)

== Edges

.Changed edges
New Powers (SWADE p 47)::
//An arcane character may learn two new powers by choosing this Edge (which may be taken multiple times). He may choose from any powers of his Rank or lower normally available to his particular Arcane Background.
//A character can add a new Trapping on a power she already has instead of gaining a new one. She might add an ice Trapping to her existing fire bolt, for example, so she could switch between ice and fire Trappings freely.
Renamed as "New Power and New Trapping" + 
The weird scientist adds *one* new power by choosing this Edge (which may be taken multiple times) _and_ one new power trapping.
For the new power, the hero may choose from any powers of her Rank or lower that are normally available to Arcane Background (Weird Science).
For the new trapping, the hero adds an effect to an existing power.
For example, the player might add an electrical trapping to her hero's existing freeze bolt; she can then switch between shock and cold trappings.

.Removed Edges
* Linguist (as per the Multiple Languages setting rules in SWADE p 149)
* See <<#arcane_bg>> below for other unavailable edges
// * Arcane Resistance (SWADE p 37) and Improved Arcane Resistance
// * Giant Killer (SWADE p 42)

[[arcane_bg]]
=== Arcane Backgrounds

Only the Weird Science arcane background is available for heroes. 
Edges that are associated with unavailable arcane backgrounds are not available to heroes.

.Why No Psionics?
****
In this setting, heroes do not control the minds of others, wipe others' memories, and project mental blasts. 
Let's focus on fists, bullets, and car chases and leave the superhuman and supernatural stuff to the big villains.
****

The unavailable edges are:

** Extra Effort (SWADE p 46)
** Holy/Unholy Warrior (SWADE p 46)
** Mentalist (SWADE p 46)
** Wizard (SWADE p 47)

.Men of Mystery and Street-Level Superheroes
****
If we were to build heroes such as the _The Shadow_ and _Doc Savage_, we'd likely be using the Arcane Backgrounds of Gifted or Psionics.
In this campaign, we are focusing on a low-powered, classic pulp adventure game _a la_ the Indiana Jones movies or the Mummy series.
****


////
The following arcane backgrounds are allowed for villains:

* Weird science
* Psionics
* Magic
////

== Hindrances

Cocky (minor)::
The character is a braggart and will typically spend the first round of any combat announcing how great he is, or what he's going to do to any and all opponents.
Cocky is like a minor version of the Overconfident (major) hindrance (SWADE p 26). 

== Powers

Fly (SWADE p 162)::
For heroes with the Arcane Background (Weird Science) edge, Fly is available at Novice rank.
