= Classic two-fisted pulp adventures
Andy Hall <achall@gmail.com>
v1.0, 2023-09-16
:experimental:
//:toc: left
//:toclevels: 4
// :sectlinks:
// :sectanchors:


////
 ////=== Acts and scenes

Typically, a Daring Tales of Adventure scenario was divided into 3 or 4 acts; each act usually consists of 3 or 4 scenes.
////

== Setting Rules

Savage Worlds Adventure Edition has a number of setting rules that are perfect for running a two-fisted pulp game.

* Conviction (SWADE p 136)
* Creative Combat (SWADE p 137)
* Fast Healing (SWADE p 139)
* More Skill Points (SWADE p 140)
* Multiple Languages (SWADE p 140)
* Wound Cap (SWADE p 141)
* Dumb Luck (SWADE p 138)
* Fanatics (SWADE p 138)
* Heroes Never Die (SWADE p 140)
* High Adventure (SWADE p 140)
* Wealth (xref:rules:wealth_sw.adoc[])
// Born a Hero (SWADE p 136)

////
.Why not use the Wound Cap setting rule?
****
I thought of adding the Wound Cap setting rule (SWADE p 141) but I figured that, with Fast Healing, Dumb Luck, Heroes Never Die,  <<#injuries_are_temporary>>, and  <<#nonlethal_damage_to_heroes>>, the heroes were wearing enough bubble wrap. 
There has to be _some_ danger to a character's life.
****
////

The following rules and directions further tune the setting for a classic pulp action game.


[#start_of_combat_benny]
=== Bennies

Before the start of every standard combat encounter or standard chase encounter (i.e., not before a _quick encounter_), each hero gets a benny, provided that the benny does not exceed the character's amount of bennies at the session's start. 
A typical wild card hero has 3 bennies at session start, unless the hero has edges or hindrances that affect his starting bennies.

IMPORTANT: As a player (GM included!), if you have 6 or more bennies in your stack, the GM will not award you more for role-playing, etc.
Spend your bennies, have fun with them, and trust that that the bennies will flow back to you.

==== Be the Hero

The protagonists are heroes so play them that way. 
If your protagonist commits an evil, villainous, or morally ambiguous act, expect to lose a benny. 

NOTE: This benny loss reduces the protagonist's benny maximum until the start of the next session. 
For example, if the hero typically starts a session with 3 bennies, her benny limit would then be reduced to 2 for the duration of the session.

TIP: The game master should warn the player about this rule and the consequences of the action before the player's hero commits an ignoble deed.

////
==== Soaking

When a hero soaks all of the damage from an attack, they get the benny back.
////

==== Stunts
// From Adamant Entertainment's "Thrilling Tales of Adventure"

A stunt action is any action that is performed in a flashier than normal way.
Any hero who attempts a stunt action deserves a benny.

In game terms, a stunt is an action where the player purposefully makes the action more difficult for the hero. 
A stunt action always requires a trait roll, at a minimum -2 penalty. 
The GM is the final arbiter of the roll penalty of a particular stunt action.

.Conventional action
****
Getting on board an airship before it lifts off from the platform is an action
****

.Stunt action
****
Leaping from the sidecar of a speeding motorcycle onto an airship at the last second as it lifts off from the platform.
****

=== Surrender

When the heroes surrender at a dramatically fitting place in the story and go along with the demands of the antagonists, each player takes a benny.
The GM may need to signal that we're using the "surrender" rule at this point.

== Setting the tone

// == Action, tension, and combat
Most action scenes in pulp need to be fast-paced and not get bogged down in combat mechanics.

Do not expect standard tactical combats that last beyond 3 or 4 rounds.
For a standard combat, I'll apply the "timers, threats, and treats" guidance from ICRPG.

The SWADE quick encounter mechanics will be used regularly.
The dramatic task mechanics will feature prominently.
The chase rules will be used regularly so players are encouraged to have some familiarity with them as they would the combat mechanics.


=== Cinematic death
In a pulp game death is not gory and messy.

=== Contacts

Once per adventure, one of the players can invent a Contact, who is a slightly helpful non-player character. 
A player may invent a Contact for his hero once per rank.
A contact typically serves to provide gear,  information, or clues and leads when parties are struggling. The GM gets the final decision on what the Contact provides the heroes.

////
 === Henchmen

An NPC henchman has three wounds like a wild card but, in all other respects, they are extras (that is, no wild die, no bennies for an non-player character wild card).

////

// === Heroic Combat

////
==== Damage by Extras

The damage rolls of Extras do not ace.
////

////
[[nonlethal_damage_to_heroes]]
=== Nonlethal damage to heroes

All damage taken by heroes is treated as nonlethal. 
A hero can only die if a villain performs a Finishing Move (SWADE p 101).
////

////
==== Fast healing

Heroes recover 1 wound at the start of an "Act". See <<_acts_and_scenes>>.
////

[[injuries_are_temporary]]
=== Injuries are temporary

Heroes do not suffer a permanent injury. 
When the wounds from the injury heals, the hero no longer suffers the effect of the injury.

NOTE: A character may spend a Benny at any time to make a Natural Healing roll.

=== Never-ending ammo

At the end of the scene, heroes recover all spent ammunition.
// At the end of the scene, heroes recover all spent Power Points.

////
=== Pulp fisted

Heroes never suffer the Unarmed Defender penalty (SWADE p 109).
////
////
=== Recurring villains

All of the villains that the GM wants to return in a sequel are treated as having the Harder to Kill edge (SWADE p 42) but with a 100% chance of survival.

The GM can also spend a benny to guarantee a villain's escape. The escaping villain ignores all die rolls and action limits. He cannot perform actions that he is normally incapable of taking and he cannot attack. Heroes who are on hold cannot interrupt the escape.

[WARNING]
The "Recurring villains" setting rules are a bit _too_ much. Do not get too committed to the survival of a villain. Make some allowance for the heroes to kill them off.
////

=== Police Interference

The cops do not turn up on the scene until after the action has ended.

////
== Chases

There are at least three chases per _Darting Tales of Adventure_ scenario; the _Daring Tales_ chases used different rules from those specified in the _Savage Worlds Deluxe Explorers' Edition_ rules and they are also markedly different from the
_Savage Worlds Adventure Edition_ chase rules.

Wiggy wrote some excellent set piece chase actin scenes.
If you can use these chases with minimal change, I suggest doing so. Some minor changes are needed. For example, if the chase calls for an Agility trait roll to maneuver, you will most likely want to call for the Athletics skill.

There will be cases where you may want to use a Quick Encounter to handle a chase scene. For example, you may want to keep the pace of the game going and move on to the next scene before the session ends.

=== Obstacles and Complications

As per the rules, if the action card that is dealt to a character at the start of a chase round (SWADE p 114) is a club, there's a problems of some kind;  the hero needs to make a maneuvering roll.

In standard chases, you check the chase card suit against the Complications table to determine the mechanical effect of the complication and the hero makes a maneuvering roll (SWADE p 116).

In many of the set-piece chases in _Daring Tales of Adventure_ scenarios, when the action card is a club, the GM refers to the Obstacles listed for the scene, looking up the card value to determine what's next.footnote:[See "Daring Tales of Adventure - The Devil's Chalice",  Act 1, Scene 2.] The obstacle descriptions provide useful narrative color, indicate the maneuvering penalty, and state what happens if the maneuvering roll fails.

In some _Daring Tales of Adventure_ chase scenes, the obstacles and events of a chase are fixed beforehand; the heroes are running a gauntlet.footnote:[See "Daring Tales of Adventure - The Talons of Lo-Peng",  Act 2, Scene 3.]

At the fixed event points (called increments) in the chase, stuff happens when the heroes reach that increment, no matter if they pass that stage or not.
If the scene defines 20 increments, lay down 20 chase cards. Use some kind of counter to mark the increments on which fixed events occur.
////
////
=== Success with a cost

If you roll a 1 on your skill die but your wild die is successful, the result is still considered a success, but there is a negative effect or compromise (e.g., your weapon becomes entangled in an enemy's armor). The player can describe what the negative effect looks like.
////

=== Cliffhangers

The cliffhanger is a staple of a pulp-action story.

.Examples of a cliffhanger
* being captured
* losing a piece of vital equipment
* getting to the mission objective too late
* a key NPC is abducted by the villains

Sometimes in a pulp-action story, the villains get the upper hand and the heroes suffer a setback, which they then need to overcome.
A cliffhanger is an opportunity for a player to develop her character's story and take narrative control.
The good news is that, at the end of the cliffhanger, the character comes out ahead.

The Quick Encounter rules are used to resolve a cliffhanger.

. The GM sets up a seemingly hopeless scenario and declares a cliffhanger. 
. (GM's discretion) One character can escape the initial predicament with their gear.
It is assumed that this character returns to help their teammates escape. 
. The GM tells the players the grim news of their desperate situation. 
+
NOTE: A character action cannot affect the initial predicament.
+ 
.Cliffhanger predicaments
====

.The heroes are... 
* captured, placed in a death trap, and left to die
* overcome by hazardous conditions, stranded, and left for dead 
* trapped on a runaway vehicle that they cannot control and facing certain death
* The GM will find more ways...

====
. In a series of flashbacks (Quick Encounter trait rolls), each player narrates his hero's action during the cliffhanger scene.
The results and rewards can differ depending upon the situation, the roll, and player narrative. 
If a hero fails her trait roll, she might suffer harm (e.g., fatigue, wounds) or suffer a penalty to a subsequent action.
. The GM rules on the consequence of the setback.
. The GM rewards the heroes.

.Setbacks caused by a cliffhanger situation might include
* Lost time
* Artifact lost
* Information is disclosed
* NPC is abducted (or worse)

.Rewards for overcoming a cliffhanger might include
* A benny or, in some circumstances, the replenishment of starting bennies
* A conviction token
* A new item
* New information
◦ Draw an Adventure Card and gain an additional Adventure Card Play.

.Facts about cliffhanger scenes
* Wild card (heroes and villains) cannot die
* The villains never tend to  stick around
* The big villain will likely monologue before he exits
* The cliffhanger scene takes a plot-appropriate amount of time to resolve
