= Create your pulp hero

When planning your character, make someone who would be up to thwart evil across the globe.
Of course, it is interesting if the character has some reluctance to putting herself in peril (e.g., family at home, a movie to star in, experiments to complete), but a party full of reluctant heroes who all need to be coaxed into action before an adventure creates friction in our story that we want to minimize.

TIP: You can use the setting in Savaged.us at https://savaged.us/s/fxwm2vka and click *User Setting* to create a character.
To use savaged.us, you need an account and you can create at leasts a few characters without having to pay any money.

.Pregenerated characters
****
The Daring Tales of Adventure scenarios were built with the following characters in mind

* Brent Hardcastle https://svgd.us/jm1l6ir4 - the pilot and leading man
* Doc Davenport https://svgd.us/fi6gi49h - the mad scientist
* Amelia Valentine https://svgd.us/duchess_dtoa - the skilled leading lady
* Jimmy Patterson https://svgd.us/nvqwxiou - the precocious kid

There is no reason why you cannot take one of these characters and adapt them to fit your play interests.
****

== Motivations

.Suggested motivations:
* Money
* Higher purpose (e.g., preserve, protect, redeem)
* Adventure and thrills
* Reputation, glory, and fame
* Professional rivalry
* Redemption

== Races
Heroes are humans.

== Initial rank and advances

The characters begin with 2 advances. 

== Skills

Pulp heroes are more capable than most.
At character creation, they start with 15 skill points as per the "More skill points" setting rule.

.Changed skills
// * Electronics is reskinned as Gadgetry
* Hacking is reskinned as Cryptopgraphy + 
It assumes some knowledge of codes and code breaking (e.g., Morse code) and mathematics

.Removed skills
* Focus, applies to the Arcane Background (Gifted)
* Faith, applies to the Arcane Background (Miracles)
* Language (see the Multiple Languages setting rules in SWADE p 149)
* Psionics, applies to the Arcane Background (Psionics)
* Spellcasting, applies to the Arcane Background (Magic)

== Edges

.Changed edges
New Powers (SWADE p 47)::
//An arcane character may learn two new powers by choosing this Edge (which may be taken multiple times). He may choose from any powers of his Rank or lower normally available to his particular Arcane Background.
//A character can add a new Trapping on a power she already has instead of gaining a new one. She might add an ice Trapping to her existing fire bolt, for example, so she could switch between ice and fire Trappings freely.
Renamed as "New Power and New Trapping" + 
The weird scientist adds *one* new power by choosing this Edge (which may be taken multiple times) _and_ one new power trapping.
For the new power, the hero may choose from any powers of her Rank or lower that are normally available to Arcane Background (Weird Science).
For the new trapping, the hero adds an effect to an existing power.
For example, the player might add an electrical trapping to her hero's existing freeze bolt; she can then switch between shock and cold trappings.

.Removed Edges
* Linguist (as per the Multiple Languages setting rules in SWADE p 149)
* See <<#arcane_bg>> below for other unavailable edges
// * Arcane Resistance (SWADE p 37) and Improved Arcane Resistance
// * Giant Killer (SWADE p 42)

[[arcane_bg]]
=== Arcane Backgrounds

Only the Weird Science arcane background is available for heroes. 
Edges that are associated with unavailable arcane backgrounds are not available to heroes.

.Why No Psionics?
****
In this setting, heroes do not control the minds of others, wipe others' memories, and project mental blasts. 
Let's focus on fists, bullets, and car chases and leave the superhuman and supernatural stuff to the big villains.
****

The unavailable edges are:

** Extra Effort (SWADE p 46)
** Holy/Unholy Warrior (SWADE p 46)
** Mentalist (SWADE p 46)
** Wizard (SWADE p 47)

.Men of Mystery and Street-Level Superheroes
****
If we were to build heroes such as the _The Shadow_ and _Doc Savage_, we'd likely be using the Arcane Backgrounds of Gifted or Psionics.
In this campaign, we are focusing on a low-powered, classic pulp adventure game _a la_ the Indiana Jones movies or the Mummy series.
****


////
The following arcane backgrounds are allowed for villains:

* Weird science
* Psionics
* Magic
////

== Hindrances

Cocky (minor)::
The character is a braggart and will typically spend the first round of any combat announcing how great he is, or what he's going to do to any and all opponents.
Cocky is like a minor version of the Overconfident (major) hindrance (SWADE p 26). 

== Powers

Fly (SWADE p 162)::
For heroes with the Arcane Background (Weird Science) edge, Fly is available at Novice rank.

== Starting resources

$500 as per SWADE.

[#advance_xp]
== Advancement and experience points

NOTE: The following rules on experience points and advances originate from _Savage Worlds Deluxe Explorer's Edition_ (p 42).
If a rule is not adjusted here, assume that we are using the SWADE rules on "Advancement" (p 54).

Most VTT sessions we play are 2.5 h long or less.

A character will typically receive 1-2 experience points per session.
All characters are awarded the same number of experience points.

Every 5 experience points that a character accumulates 
grants 1 Advance.

If a player is absent from a session, his character does not receive experience points.

=== Ranks
As a character gains more Experience Points, he goes up in “Rank.” 

This is a rough measure of how powerful the hero is. As characters progress in experience, new Ranks allow access to more powerful Edges.

.Rank Table
[%autowidth]
|===
| Experience Points | Rank

| 0-19 | Novice
| 20-39 | Seasoned
| 40-59 | Veteran
| 60-79 | Heroic
| 80+ | Legendary
|===

Once a hero reaches Legendary status, the rules for Advances change a bit. 
The character now Advances every time he accumulates 10 Experience Points instead of 5, but a world of new Edges opens up to him as well. 

