
// :dtoa: Daring Tales of Adventure 

= Playing the pulp action game

The players, the GM included, are trying to mimic pulp action films.
The heroes are very hard to kill; they perform daring deeds and take extreme risks. 

// == Expectations for the Pulp Action Campaign
////
.Player Attendance
****
Players must commit to attend each session of a scenario.
Don't ask for a longer commitment.
A {dtoa} scenario typically runs for 3-4 sessions of 2.5-3 hours.
****
////


// We are using the Savage Worlds Adventure Edition (SWADE) rules.

// * Determine setting rules up front and keep houseruling to a minimum
// * Unless we state otherwise, heroes are awarded an average of 1 advance every 2 sessions
// * If you miss a session, you get no credit for an advance and your character will operate as an allied extra

//<!-- * After a few sessions, I expect players to have a licensed copy of the SWDEE (an affordable $10 USD) -->

// == When we're playing Savage Worlds

[#expectations]
.Expectations
* We want to follow the "Fast, Furious, and Fun" ethos.
Do your part to keep the pace of the game relatively brisk.
// * We're playing on a virtual tabletop (likely Roll20); I am not planning to over-invest in visual aids unless they are especially evocative.
// * Learn the Roll20 technology for Savage Worlds but you do not need to know Roll20 when you first join
** Learn the Savage Worlds rules; if you're new to Savage Worlds rules, you can download the most recent https://www.peginc.com/tag/test-drive-rules/[Savage Worlds Test Drive]
** If you have any rules for your character's schticks (e.g., arcane powers or gambling), learn them or have the rules handy
* The GM awards bennies for playing your hero according to the tone of the game and playing his hindrances in such a way as they hinder the character or party
** I think that awarding bennies to a player for good role playing or for "doing cool things" is too subjective and ambiguous 
// * You'll get bennies for trying to do cool things, making the game fun and interesting, playing according to the tone, and playing hindrances
* Bring your imagination and a willingness to narrate and add to the story footnote:[https://thealexandrian.net/wordpress/44891/roleplaying-games/gm-dont-list-11-description-on-demand and https://gamingandbs.com/descriptions-on-demand-in-rpgs-gbs308/]
* Be engaged during the game session and do your best to pay attention
* Share the stage so your fellow players can shine
// * Plan to make the game entertaining, interesting, and challenging
* If you cannot attend the game at the specified time, give reasonable advanced notice
* Give the GM feedback on what is working well, what you want to see more of, and what could use some work
* Prepare to engage in an adult conversation if we ever need to course correct
// * Be open to trying new tools for communication
* Stay classy

////
== Goals

As a GM and player, I have these goals:

* To build some memorable gaming stories together
* Make the game fun, or at least engaging, for all involved
* To become a better GM; to develop as player
* To encourage and help other players and GMs
////

[#session_zero]
== Session zero

.Objectives of session zero:
* Introductions and meet-up
* Discuss expectations of the game
* Determine character concepts and roles in the party
** Identify character hindrances and interesting aspects
** Determine relationships/bonds between characters 


=== Introductions

Basics:: Name, Location, TTRPG Experience, and anything else you want to share
What things about Savage Worlds (and/or RPGs in general) do you enjoy?:: Combat, Puzzles, Roleplay, etc
What is one strength you bring to the group?:: Maybe it's your experience, your consistency, your voice acting, your creativity, your keen grasp of the rules, or just being all around fun to play with. 
 
=== Scheduling and the gaming group

Time and Date of Games:: Games will happen on Wednesday evenings at 8 pm EST. 
I'd like to aim for three sessions every 4-5 weeks. 
Attendance:: As long as we have 3 players, we will run a session. If we ever have fewer than 3, we'll reschedule.
Session Length:: A session will last about 2.5 hours (so 10:30 PM EST is the typical end). 

=== Communications Tools and Table Expectations
Safety Tools:: I've never used them but that does not mean we should not. This game is supposed to be run as a PG-13 movie. I want to be cognizant of ethnic and sexist stereotypes. 
Open Door:: Feel free to reach out to me to discuss points about the game, etc.
Off Limits Topics:: Transphobia, Homophobia, Graphic violence directed towards children, Graphic depictions of torture

=== GM style

Look up the rules later:: 
If there's a question about rules, I'll probably make a call (typically in favor of the players) and then look up the rule later. 
If I make a bad call, we'll figure out how to make it right. 
I know we have some expert Savages in the crew who know the rules well and I may ask for help with a quick rule look-up. 
Encumbrance rules? No thanks:: Just be reasonable about what your hero is carrying. 
Golden Hour:: I'm indifferent to the golden hour rule and I will forget it. 
If you really think it should be applied, remind me and we can apply it. 
Money and Resources:: I'm pretty hand-wavy on this stuff. 
I hope that's OK.
Tone:: I'm usually shooting for 60% serious and 40% silly/fun. 

=== Our Table

Character Death:: It is hard to kill a player in a Savage Worlds pulp action game but it might happen. 
If you want your character to die (e.g., a heroic death), let's discuss that subject in advance and see how this might be meaningful to the overall story.
PVP:: I'm inclined to avoid PVP but it can also add spice to a story. If there is PVP and mechanics need to be engaged, expect that we'll adapt the social conflict mechanics (or possibly use the quick encounter mechanics).
Dice:: We're going to roll dice in Roll20. All of my dice rolls will be in the open.  
Shared Background and Character Bonds:: I am looking to adapt something (e.g., the bonds mechanic from PbtA) but I am open to ideas.
