= Rippers: Regency

The game setting is loosely set in the first quarter of the 19th century, likely between 1815 and 1840.
This period overlaps with the late https://en.wikipedia.org/wiki/Regency_era[Regency era, window="_blank"].

During the Regency era, there are many differences from the canon Rippers setting:

* _rippen transferre_ experiments are considered part of the larger body of mad and weird science
** The term "Rippertech" has not been coined. 
** The integration of _rippen-transferre_, now going by the name of _Rippen technologie_, into humans is known to corrupt a man's mind and soul. + 
Surely, no good can come of it!
It is a pursuit of madmen and deviants. + 
* There is nothing resembling the Rippers organization of the late Victorian period
** There is no network of Ripper lodges
* The technology level is early industrial.
This affects on combat and travel.
Black powder weapons are used and, as a result, there's more close combat and fewer lead projectiles.
* The field of psychiatry, not to mention modern medical science, is in its infancy.
If you were deemed insane, you would be locked away in a madhouse, to suffer and likely die in squalor. 
See https://www.ashfordstpeters.nhs.uk/19th-century-mental-health[19th Century Mental Health, window="_blank"].
* The protagonists are relatively normal people who are pulled into a world of gothic horror.
+ 
CAUTION: This is not a superhero game.
The heroes _are_ squishy.


.Inspirations
* Taboo - limited tv series
* Jonathan Strange and Dr. Norrell - book and miniseries
* The Count of Monte Cristo - book and films
* The Frankenstein Chronicles - tv series
* Brotherhood of the Wolf - movie
* The Revenant - movie

== Resources

* https://www.romanticlondon.org/maps/fullscreen/layer/26/#13/51.5077/-0.0740[Map of London in 1819] + 
This is William Faden's Fourth Edition of Horwood's Plan (1819). 
It is a digitized and fully scalable.

ifdef::github-env[]
== Story ideas
* I think there's a story to tell where the PCs work with the antagonist, an esteemed personage, but then have to counter him as he slips into madness. 

=== Savage Tales

* Pyramid Power (OGR 77)
* Frankenstein Unbound (OGR 82)
* Artificial Light (OGR 94)
* The Scarab (OGR 95)
endif::github-env[]

