= Savage Worlds Lankhmar

[quote, Andy]
____
In the city of Sevenscore Thousand Smokes, you live by your wits, carve out your territory, and then some weird shit is bound to happen.
____

.Genre
****
In terms of the the _Savage Worlds Adventure Edition Fantasy Companion_ (FC), the genre and tone is a combination of "Low Fantasy" and "Dark Fantasy".
****

== Setting rules

We're largely using the rules as set put in LCoT but there are a few differences.

.The setting rules we use are:
* Betrayal - FC p 76 (replaces "No honor among thieves" from LCoT)
* Unarmored Hero - SWADE p 141 (replaces "Unarmored heroes" from LCoT)
* Fast Healing - SWADE p 139 (replaces "Larger than life" from LCoT)
* Knockout Blow (SWADE p 100) is a standard SWADE rule
// * Dynamic Backlash
// * Hard Choices (&#x2021;)
// * New Power (&#x2020;) edge

=== Down to my last tik
Each game week, a character halves his total funds. 
A character with the Poverty hindrance quarters his funds each week.
See LCoT 24.

=== Guilds
See LCoT 24-25.

=== Heists

We'll leverage the heist rules and generator from the Wiseguys setting.

=== Street Gangs

We'll leverage the street gang generator from the Wiseguys setting but we'll make some adaptations.



[[no_ab]]
=== No arcane backgrounds for player characters

The player characters do not have arcane backgrounds.

== Character creation

=== Starting experience

Player characters start at Seasoned rank (4 advances).

=== Skills

Characters begin with a d4 in Athletics, Stealth, Notice, and Persuasion.

As per the standard SWADE rules, characters start with 12 points to allocate to skills.


==== Changed Skills

* Hacking is recast as "Cryptography and Ciphers"
* Academics covers scientific subjects so there is no need for a Science skill
* Riding also covers the driving of animal-propelled vehicles such as wagons and chariots


==== Removed Skills

.Removed arcane background-related skills
* Focus, applies to the Arcane Background (Gifted)
* Faith, applies to the Arcane Background (Miracles)
* Psionics, applies to the Arcane Background (Psionics)
* Spellcasting, applies to the Arcane Background (Magic)
* Weird Science, applies to the Arcane Background (Weird Science)
//* Language (see the Multiple Languages setting rules in SWADE p 140)

.Other removed skills
* Electronics
* Piloting
* Science

=== Edges

Edges that support arcane backgrounds (or have arcane background requirements) and related powers are off limits to player characters.
See also <<#no_ab>>.

Refer to the _Lankhmar conversion document for SWADE_, LCT, and LSSoN.




// === Changes to edges

////
==== New Power (SWADE p 47)  
The character adds **one** new power by choosing this Edge (which may be taken multiple times) *and* one new power trapping.
For the new power, the character may choose from any powers of her Rank or lower that are normally available to his Arcane Background.
For the new trapping, the hero adds an effect to an existing power.
For example, the hero might add an electrical Trapping to her existing freeze entangle power, for example, so she could switch between shock and cold Trappings.
////

.References:
* Lankhmar: City of Thieves (LCoT)
* Lankhmar: Savage Seas of Nehwon (LSSoN)
* Savage Worlds Adventure Edition Fantasy Companion (FC)
* Savage Worlds Adventure Edition (SWADE)
* https://peginc.com/store/lankhmar-conversion-for-adventure-edition-pdf-swade/[Lankhmar conversion document for SWADE]