graph TD
    Tejon["Tejon the Hangman (Monk)"]
    Dorgan["Dorgan the Scholar (Rogue)"]
    Ronjon["Ronjon the Barkeep (Bard)"]
    Andy["Andy the Unknown (Unknown)"]

    Dorgan <-- "Survivors of the Great March" --> Ronjon
    Ronjon <-- "Body servants of the Bandit Lord" --> Tejon
    Tejon <-- "Bodyguard duties" --> Andy
