flowchart TD

    Tejon["Tejon the Hangman (Monk)"]
    Dorgan["Dorgan the Scholar (Rogue)"]
    Ronjon["Ronjon the Barkeep (Bard)"]
    Andy["Andy the Unkown (Unknown)"]


    Dorgan -- "Survivors of the Great March" --> Ronjon
    Tejon -- "Body servants of the Bandit Lord --> Ronjon
    Tejon -- "Bodyuard" --> Andy   
