graph TD
    Tejon["Tejon the Hangman (Monk)"]
    Dorgan["Dorgan the Scholar (Rogue)"]
    Ronjon["Ronjon the Barkeep (Bard)"]
    Leafsong["Leafsong the Wanderer (Ranger)"]
    Ash["Ashwyllyms the Fierce (Barbarian)"]

    Dorgan <-- "Survivors of the Great March" --> Ronjon
    Ronjon <-- "Body servants of the Bandit Lord" --> Tejon
    Tejon <-- "Bodyguard duties" --> Leafsong
    Leafsong  <-- "Captives for a brief time" --> Ash
    Ash  <-- "Deceased mentor" --> Dorgan

